apiVersion: apps/v1
kind: Deployment
metadata: 
  name: patient-service
  labels:
    app: patient-service

spec:
  replicas: 2

  selector:
    matchLabels:
      app: patient-service

  template:
    metadata:
      labels:
        app: patient-service
    
    spec:
      containers:
      - name: patient-service

        image: 584135072796.dkr.ecr.us-east-1.amazonaws.com/patient-service:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 3000

        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi

        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20

        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10